#CS.3#diagonal
import turtle
s=turtle.Screen()
t=turtle.Turtle()
t.pensize(5)
t.pencolor('red')
s.bgcolor("black")
t.left(45)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
